server:
  servlet:
    context-path: '/weather-history'
  port: 8081

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:librarydb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create-drop