server:
  servlet:
    context-path: /weather-history
    application-display-name: weather-history-service
  port: 8081

spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:historydb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
