server:
  port: 8081

spring:
  application:
    name: weather-history
  webflux:
    base-path: /weather-history
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/weather
    username: admin
    password: password
  liquibase:
    url: jdbc:postgresql://postgres:5432/weather
    change-log: classpath:db/db.changelog.yml
    user: admin
    password: password